version: "3.9"

services:
  db:
    image: mysql:5.7
    container_name: godb
    ports:
      - "6666:3306"
    volumes:
      - "./database:/docker-entrypoint-initdb.d"
    restart: always
    environment:
      
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bibli
